/*
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package Model;

import org.openapitools.client.model.BankAccountDeletion;
import org.testng.annotations.Test;


/**
 * Model tests for BankAccountDeletion
 */
public class BankAccountDeletionTest {
    private final BankAccountDeletion model = new BankAccountDeletion();

    /**
     * Model tests for BankAccountDeletion
     */
    @Test
    public void testBankAccountDeletion() {
        // TODO: test BankAccountDeletion
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'deleted'
     */
    @Test
    public void deletedTest() {
        // TODO: test deleted
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

}
