/*
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package Model;

import org.openapitools.client.model.SortBy;
import org.testng.annotations.Test;


/**
 * Model tests for SortBy
 */
public class SortByTest {
    private final SortBy model = new SortBy();

    /**
     * Model tests for SortBy
     */
    @Test
    public void testSortBy() {
        // TODO: test SortBy
    }

    /**
     * Test the property 'dateCreated'
     */
    @Test
    public void dateCreatedTest() {
        // TODO: test dateCreated
    }

    /**
     * Test the property 'sendDate'
     */
    @Test
    public void sendDateTest() {
        // TODO: test sendDate
    }

}
