/*
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package Model;

import org.openapitools.client.model.ZipEditable;
import org.testng.annotations.Test;


/**
 * Model tests for ZipEditable
 */
public class ZipEditableTest {
    private final ZipEditable model = new ZipEditable();

    /**
     * Model tests for ZipEditable
     */
    @Test
    public void testZipEditable() {
        // TODO: test ZipEditable
    }

    /**
     * Test the property 'zipCode'
     */
    @Test
    public void zipCodeTest() {
        // TODO: test zipCode
    }

}
