/*
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lob.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import java.util.HashMap;
import java.util.Map;
/**
 * EventType
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class EventType {
  public static final String SERIALIZED_NAME_ID = "id";

  @SerializedName(SERIALIZED_NAME_ID)
  

  private String id;
  /**
  * Get id
  * @return id
  **/
  
  @javax.annotation.Nonnull
  
  @ApiModelProperty(required = true, value = "")
  
  public String getId() {
      return id;
  }
  
  

  public static final String SERIALIZED_NAME_ENABLED_FOR_TEST = "enabled_for_test";

  @SerializedName(SERIALIZED_NAME_ENABLED_FOR_TEST)
  

  private Boolean enabledForTest;
  /**
  * Value is `true` if the event type is enabled in both the test and live environments.
  * @return enabledForTest
  **/
  
  @javax.annotation.Nonnull
  
  @ApiModelProperty(required = true, value = "Value is `true` if the event type is enabled in both the test and live environments.")
  
  public Boolean getEnabledForTest() {
      return enabledForTest;
  }
  
  

  /**
   * Gets or Sets resource
   */
  @JsonAdapter(ResourceEnum.Adapter.class)
  public enum ResourceEnum {
    POSTCARDS("postcards"),
    
    SELF_MAILERS("self mailers"),
    
    LETTERS("letters"),
    
    CHECKS("checks"),
    
    ADDRESSES("addresses"),
    
    BANK_ACCOUNTS("bank accounts");

    private String value;

    ResourceEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ResourceEnum fromValue(String value) {
      for (ResourceEnum b : ResourceEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ResourceEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ResourceEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ResourceEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ResourceEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_RESOURCE = "resource";

  @SerializedName(SERIALIZED_NAME_RESOURCE)
  

  private ResourceEnum resource;
  /**
  * Get resource
  * @return resource
  **/
  
  @javax.annotation.Nonnull
  
  @ApiModelProperty(required = true, value = "")
  
  public ResourceEnum getResource() {
      return resource;
  }
  
  

  /**
   * Value is resource type.
   */
  @JsonAdapter(ObjectEnum.Adapter.class)
  public enum ObjectEnum {
    EVENT_TYPE("event_type");

    private String value;

    ObjectEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ObjectEnum fromValue(String value) {
      for (ObjectEnum b : ObjectEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ObjectEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ObjectEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ObjectEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ObjectEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_OBJECT = "object";

  @SerializedName(SERIALIZED_NAME_OBJECT)
  

  private ObjectEnum _object = ObjectEnum.EVENT_TYPE;
  /**
  * Value is resource type.
  * @return _object
  **/
  
  @javax.annotation.Nonnull
  
  @ApiModelProperty(required = true, value = "Value is resource type.")
  
  public ObjectEnum getObject() {
      return _object;
  }
  
  


  /*
  public EventType id(String id) {
    
    this.id = id;
    return this;
  }
  */


  public void setId(String id) {
    this.id = id;
  }



  /*
  public EventType enabledForTest(Boolean enabledForTest) {
    
    this.enabledForTest = enabledForTest;
    return this;
  }
  */


  public void setEnabledForTest(Boolean enabledForTest) {
    this.enabledForTest = enabledForTest;
  }



  /*
  public EventType resource(ResourceEnum resource) {
    
    this.resource = resource;
    return this;
  }
  */


  public void setResource(ResourceEnum resource) {
    this.resource = resource;
  }



  /*
  public EventType _object(ObjectEnum _object) {
    
    this._object = _object;
    return this;
  }
  */


  public void setObject(ObjectEnum _object) {
    this._object = _object;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    EventType eventType = (EventType) o;
    return Objects.equals(this.id, eventType.id) &&
        Objects.equals(this.enabledForTest, eventType.enabledForTest) &&
        Objects.equals(this.resource, eventType.resource) &&
        Objects.equals(this._object, eventType._object);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, enabledForTest, resource, _object);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("{\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    enabledForTest: ").append(toIndentedString(enabledForTest)).append("\n");
    sb.append("    resource: ").append(toIndentedString(resource)).append("\n");
    sb.append("    _object: ").append(toIndentedString(_object)).append("\n");
    sb.append("}");
    return sb.toString();
  }

    public Map<String, Object> toMap() {
      Map<String, Object> localMap = new HashMap<String, Object>();
      localMap.put("id", id);
      localMap.put("enabled_for_test", enabledForTest);
      localMap.put("resource", resource);
      localMap.put("object", _object);
      return localMap;
    }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

