/*
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lob.api.client;

import com.lob.api.ApiException;
import com.lob.model.PlaceholderModel;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.testng.annotations.*;

/**
 * API tests for DefaultApi
 */
@Test(enabled=false)
public class DefaultApiTest {

    private final DefaultApi api = new DefaultApi();

    
    /**
     * placeholder_no_call
     *
     * Don&#39;t call this. It&#39;s so that the right models can be generated.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test(enabled=false)
    public void placeholderTest() throws ApiException {
                PlaceholderModel response = api.placeholder();
        // TODO: test validations
    }
    
}
