/*
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lob.api.client;

import com.lob.api.ApiException;
import com.lob.model.LobError;
import com.lob.model.MultipleComponentsList;
import com.lob.model.UsVerification;
import com.lob.model.UsVerifications;
import com.lob.model.UsVerificationsWritable;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.testng.annotations.*;

/**
 * API tests for UsVerificationsApi
 */
@Test(enabled=false)
public class UsVerificationsApiTest {

    private final UsVerificationsApi api = new UsVerificationsApi();

    
    /**
     * verifyBulk
     *
     * Verify a list of US or US territory addresses with a live API key.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test(enabled=false)
    public void bulkUsVerificationsTest() throws ApiException {
        MultipleComponentsList multipleComponentsList = null;
        String _case = null;
                UsVerifications response = api.bulkUsVerifications(multipleComponentsList, _case);
        // TODO: test validations
    }
    
    /**
     * verifySingle
     *
     * Verify a US or US territory address with a live API key.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test(enabled=false)
    public void usVerificationTest() throws ApiException {
        UsVerificationsWritable usVerificationsWritable = null;
        String _case = null;
                UsVerification response = api.usVerification(usVerificationsWritable, _case);
        // TODO: test validations
    }
    
}
