/*
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lob.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import org.openapitools.jackson.nullable.JsonNullable;
import org.testng.annotations.*;


/**
 * Model tests for CardUpdatable
 */
public class CardUpdatableTest {
    private final CardUpdatable model = new CardUpdatable();

    /**
     * Model tests for CardUpdatable
     */
    @Test
    public void testCardUpdatable() {
        // TODO: test CardUpdatable
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'autoReorder'
     */
    @Test
    public void autoReorderTest() {
        // TODO: test autoReorder
    }

    /**
     * Test the property 'reorderQuantity'
     */
    @Test
    public void reorderQuantityTest() {
        // TODO: test reorderQuantity
    }

}
