/*
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lob.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lob.model.DpvFootnote;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.testng.annotations.*;


/**
 * Model tests for DeliverabilityAnalysis
 */
public class DeliverabilityAnalysisTest {
    private final DeliverabilityAnalysis model = new DeliverabilityAnalysis();

    /**
     * Model tests for DeliverabilityAnalysis
     */
    @Test
    public void testDeliverabilityAnalysis() {
        // TODO: test DeliverabilityAnalysis
    }

    /**
     * Test the property 'dpvConfirmation'
     */
    @Test
    public void dpvConfirmationTest() {
        // TODO: test dpvConfirmation
    }

    /**
     * Test the property 'dpvCmra'
     */
    @Test
    public void dpvCmraTest() {
        // TODO: test dpvCmra
    }

    /**
     * Test the property 'dpvVacant'
     */
    @Test
    public void dpvVacantTest() {
        // TODO: test dpvVacant
    }

    /**
     * Test the property 'dpvActive'
     */
    @Test
    public void dpvActiveTest() {
        // TODO: test dpvActive
    }

    /**
     * Test the property 'dpvFootnotes'
     */
    @Test
    public void dpvFootnotesTest() {
        // TODO: test dpvFootnotes
    }

    /**
     * Test the property 'ewsMatch'
     */
    @Test
    public void ewsMatchTest() {
        // TODO: test ewsMatch
    }

    /**
     * Test the property 'lacsIndicator'
     */
    @Test
    public void lacsIndicatorTest() {
        // TODO: test lacsIndicator
    }

    /**
     * Test the property 'lacsReturnCode'
     */
    @Test
    public void lacsReturnCodeTest() {
        // TODO: test lacsReturnCode
    }

    /**
     * Test the property 'suiteReturnCode'
     */
    @Test
    public void suiteReturnCodeTest() {
        // TODO: test suiteReturnCode
    }

}
