/*
 * Lob
 * The Lob API is organized around REST. Our API is designed to have predictable, resource-oriented URLs and uses HTTP response codes to indicate any API errors. <p> Looking for our [previous documentation](https://lob.github.io/legacy-docs/)? 
 *
 * The version of the OpenAPI document: 1.3.0
 * Contact: lob-openapi@lob.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.lob.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.lob.model.BulkError;
import com.lob.model.IntlComponents;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.jackson.nullable.JsonNullable;
import org.testng.annotations.*;


/**
 * Model tests for IntlVerificationOrError
 */
public class IntlVerificationOrErrorTest {
    private final IntlVerificationOrError model = new IntlVerificationOrError();

    /**
     * Model tests for IntlVerificationOrError
     */
    @Test
    public void testIntlVerificationOrError() {
        // TODO: test IntlVerificationOrError
    }

    /**
     * Test the property 'id'
     */
    @Test
    public void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'recipient'
     */
    @Test
    public void recipientTest() {
        // TODO: test recipient
    }

    /**
     * Test the property 'primaryLine'
     */
    @Test
    public void primaryLineTest() {
        // TODO: test primaryLine
    }

    /**
     * Test the property 'secondaryLine'
     */
    @Test
    public void secondaryLineTest() {
        // TODO: test secondaryLine
    }

    /**
     * Test the property 'lastLine'
     */
    @Test
    public void lastLineTest() {
        // TODO: test lastLine
    }

    /**
     * Test the property 'country'
     */
    @Test
    public void countryTest() {
        // TODO: test country
    }

    /**
     * Test the property 'coverage'
     */
    @Test
    public void coverageTest() {
        // TODO: test coverage
    }

    /**
     * Test the property 'deliverability'
     */
    @Test
    public void deliverabilityTest() {
        // TODO: test deliverability
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'components'
     */
    @Test
    public void componentsTest() {
        // TODO: test components
    }

    /**
     * Test the property '_object'
     */
    @Test
    public void _objectTest() {
        // TODO: test _object
    }

    /**
     * Test the property 'error'
     */
    @Test
    public void errorTest() {
        // TODO: test error
    }

}
